version: '3.9'

services:
  overlap-avalara:
    build:
      context: .
      dockerfile: Dockerfile
    image: overlap-avalara:latest
    container_name: overlap-avalara
    ports:
      - '8081:8081'
    volumes:
      - ./config:/app/config:ro
    restart: unless-stopped
